import type { Creator } from "@/lib/mock-data";

export type CreatorCategory =
  | "All"
  | "Fitness"
  | "Entertainment"
  | "Trading"
  | "Podcasts"
  | "Music"
  | "Art"
  | "Adult";

export const CATEGORIES: readonly CreatorCategory[] = [
  "All",
  "Fitness",
  "Entertainment",
  "Trading",
  "Podcasts",
  "Music",
  "Art",
  "Adult",
] as const;

export interface ExploreCreator extends Creator {
  readonly id: string;
  readonly primaryCategory: CreatorCategory;
  readonly isFeatured: boolean;
}

export const EXPLORE_CREATORS: readonly ExploreCreator[] = [
  // Fitness creators
  {
    id: "fit-001",
    username: "ironmikefitness",
    displayName: "Iron Mike Fitness",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=ironmike",
    bannerUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    bio: "IFBB Pro athlete. Daily workout programs, meal plans, and live coaching sessions. Transform your physique.",
    isVerified: true,
    categories: ["Fitness", "Nutrition"],
    primaryCategory: "Fitness",
    subscriptionPrice: 14.99,
    stats: { posts: 892, subscribers: 24_800, likes: 312_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "fit-002",
    username: "flexqueenrae",
    displayName: "FlexQueen Rae",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=flexqueen",
    bannerUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    bio: "Strength training, powerlifting, and body positivity. Programs for all levels. Glute gains guaranteed.",
    isVerified: true,
    categories: ["Fitness", "Lifestyle"],
    primaryCategory: "Fitness",
    subscriptionPrice: 9.99,
    stats: { posts: 654, subscribers: 18_200, likes: 198_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "fit-003",
    username: "zenflowjake",
    displayName: "ZenFlow Jake",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=zenflow",
    bannerUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    bio: "Yoga, mobility, and mindful movement. Breathwork sessions and flexibility programs for athletes.",
    isVerified: false,
    categories: ["Fitness", "Wellness"],
    primaryCategory: "Fitness",
    subscriptionPrice: 7.99,
    stats: { posts: 423, subscribers: 9_400, likes: 67_000 },
    posts: [],
    isFeatured: false,
  },

  // Entertainment / Adult creators
  {
    id: "ent-001",
    username: "lunavelvet",
    displayName: "Luna Velvet",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=lunavelvet",
    bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    bio: "Exclusive lifestyle content, behind-the-scenes, and personal vlogs. VIP messaging available.",
    isVerified: true,
    categories: ["Entertainment", "Lifestyle"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 19.99,
    stats: { posts: 2_340, subscribers: 67_500, likes: 890_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "ent-002",
    username: "chasewilde",
    displayName: "Chase Wilde",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=chasewilde",
    bannerUrl: "https://images.unsplash.com/photo-1579547945413-497e1b99dac0?w=800&q=80",
    bio: "Comedy skits, roast sessions, and unfiltered takes. The content your timeline is too afraid to post.",
    isVerified: true,
    categories: ["Entertainment", "Comedy"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 12.99,
    stats: { posts: 1_105, subscribers: 31_200, likes: 445_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "adult-001",
    username: "scarlettraven",
    displayName: "Scarlett Raven",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=scarlett",
    bannerUrl: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=800&q=80",
    bio: "Exclusive 18+ content. Custom requests. Daily posts. Free trial for new subscribers.",
    isVerified: true,
    categories: ["Adult", "Lifestyle"],
    primaryCategory: "Adult",
    subscriptionPrice: 24.99,
    stats: { posts: 4_200, subscribers: 89_300, likes: 1_230_000 },
    posts: [],
    isFeatured: true,
  },

  // Trading / Crypto creators
  {
    id: "trade-001",
    username: "cryptosamurai",
    displayName: "CryptoSamurai",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=samurai",
    bannerUrl: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&q=80",
    bio: "On-chain alpha. DeFi strategies, memecoin calls, and portfolio breakdowns. 400%+ ROI in 2025.",
    isVerified: true,
    categories: ["Trading", "Crypto"],
    primaryCategory: "Trading",
    subscriptionPrice: 49.99,
    stats: { posts: 1_870, subscribers: 42_100, likes: 567_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "trade-002",
    username: "wallstwhale",
    displayName: "WallSt Whale",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=whale",
    bannerUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    bio: "Equities, options flow, and macro analysis. Institutional-grade research for retail traders.",
    isVerified: true,
    categories: ["Trading", "Finance"],
    primaryCategory: "Trading",
    subscriptionPrice: 29.99,
    stats: { posts: 780, subscribers: 15_600, likes: 234_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "trade-003",
    username: "nftdegen",
    displayName: "NFT Degen",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=nftdegen",
    bannerUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    bio: "NFT flips, mint alerts, and Web3 alpha. Early access to curated collections and whitelist spots.",
    isVerified: false,
    categories: ["Trading", "NFT"],
    primaryCategory: "Trading",
    subscriptionPrice: 19.99,
    stats: { posts: 520, subscribers: 8_900, likes: 112_000 },
    posts: [],
    isFeatured: false,
  },

  // Podcast / Music creators
  {
    id: "pod-001",
    username: "midnightmikeshow",
    displayName: "Midnight Mike Show",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=midnightmike",
    bannerUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80",
    bio: "Unfiltered late-night podcast. Interviews with founders, athletes, and underground legends. No sponsors.",
    isVerified: true,
    categories: ["Podcasts", "Entertainment"],
    primaryCategory: "Podcasts",
    subscriptionPrice: 9.99,
    stats: { posts: 1_340, subscribers: 53_800, likes: 678_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "music-001",
    username: "beatsbynova",
    displayName: "Beats By Nova",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=nova",
    bannerUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    bio: "Producer extraordinaire. Exclusive beats, sample packs, and production tutorials. 10M+ streams.",
    isVerified: true,
    categories: ["Music", "Production"],
    primaryCategory: "Music",
    subscriptionPrice: 14.99,
    stats: { posts: 960, subscribers: 27_400, likes: 345_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "music-002",
    username: "acousticember",
    displayName: "Acoustic Ember",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=ember",
    bannerUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    bio: "Singer-songwriter sharing raw acoustic sessions, unreleased tracks, and songwriting breakdowns.",
    isVerified: false,
    categories: ["Music", "Singer-Songwriter"],
    primaryCategory: "Music",
    subscriptionPrice: 6.99,
    stats: { posts: 387, subscribers: 12_100, likes: 89_000 },
    posts: [],
    isFeatured: false,
  },

  // Art creators
  {
    id: "art-001",
    username: "pixelvoid",
    displayName: "PixelVoid",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=pixelvoid",
    bannerUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    bio: "Digital art, AI-generated pieces, and timelapse creation videos. Commissions open for subscribers.",
    isVerified: true,
    categories: ["Art", "Digital Art"],
    primaryCategory: "Art",
    subscriptionPrice: 11.99,
    stats: { posts: 730, subscribers: 19_700, likes: 256_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "art-002",
    username: "inkbymaeve",
    displayName: "Ink By Maeve",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=maeve",
    bannerUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    bio: "Traditional ink and watercolor. Sketchbook tours, technique breakdowns, and exclusive prints for subscribers.",
    isVerified: true,
    categories: ["Art", "Illustration"],
    primaryCategory: "Art",
    subscriptionPrice: 8.99,
    stats: { posts: 412, subscribers: 11_300, likes: 145_000 },
    posts: [],
    isFeatured: false,
  },

  // More Fitness
  {
    id: "fit-004",
    username: "calisthenicsking",
    displayName: "Calisthenics King",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=caliking",
    bannerUrl: "https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=800&q=80",
    bio: "Bodyweight mastery. Planche, muscle-up, and handstand progressions. No gym required.",
    isVerified: true,
    categories: ["Fitness", "Calisthenics"],
    primaryCategory: "Fitness",
    subscriptionPrice: 12.99,
    stats: { posts: 567, subscribers: 33_400, likes: 410_000 },
    posts: [],
    isFeatured: false,
  },

  // More Entertainment
  {
    id: "ent-003",
    username: "danistreams",
    displayName: "Dani Streams",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=dani",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    bio: "Full-time streamer. Behind-the-scenes content, exclusive VODs, and subscriber game nights.",
    isVerified: true,
    categories: ["Entertainment", "Gaming"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 7.99,
    stats: { posts: 890, subscribers: 45_600, likes: 623_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "ent-004",
    username: "pranksterpaul",
    displayName: "Prankster Paul",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=paul",
    bannerUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&q=80",
    bio: "Viral pranks and social experiments. Uncut footage and bloopers only for subscribers.",
    isVerified: false,
    categories: ["Entertainment", "Comedy"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 5.99,
    stats: { posts: 324, subscribers: 21_800, likes: 290_000 },
    posts: [],
    isFeatured: false,
  },

  // More Trading
  {
    id: "trade-004",
    username: "optionsorca",
    displayName: "Options Orca",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=orca",
    bannerUrl: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80",
    bio: "0DTE specialist. Live trade alerts, position sizing guides, and weekly P&L breakdowns.",
    isVerified: true,
    categories: ["Trading", "Options"],
    primaryCategory: "Trading",
    subscriptionPrice: 39.99,
    stats: { posts: 1_120, subscribers: 28_700, likes: 389_000 },
    posts: [],
    isFeatured: false,
  },

  // More Music
  {
    id: "music-003",
    username: "djvoltage",
    displayName: "DJ Voltage",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=voltage",
    bannerUrl: "https://images.unsplash.com/photo-1571266028243-3716f02d2d74?w=800&q=80",
    bio: "EDM producer and DJ. Exclusive mixes, sample packs, and Ableton project files. Festival sets early access.",
    isVerified: true,
    categories: ["Music", "EDM"],
    primaryCategory: "Music",
    subscriptionPrice: 11.99,
    stats: { posts: 678, subscribers: 34_200, likes: 456_000 },
    posts: [],
    isFeatured: false,
  },

  // More Podcasts
  {
    id: "pod-002",
    username: "truecrimekay",
    displayName: "True Crime Kay",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=truecrime",
    bannerUrl: "https://images.unsplash.com/photo-1504711434969-e33886168d5c?w=800&q=80",
    bio: "Deep-dive true crime investigations. Bonus episodes, case file access, and live Q&A sessions weekly.",
    isVerified: true,
    categories: ["Podcasts", "True Crime"],
    primaryCategory: "Podcasts",
    subscriptionPrice: 8.99,
    stats: { posts: 780, subscribers: 41_200, likes: 534_000 },
    posts: [],
    isFeatured: false,
  },

  // More Adult
  {
    id: "adult-002",
    username: "thevelvetfox",
    displayName: "The Velvet Fox",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=velvetfox",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80",
    bio: "Premium 18+ content. Cosplay, themed shoots, and custom requests. New posts daily.",
    isVerified: true,
    categories: ["Adult", "Cosplay"],
    primaryCategory: "Adult",
    subscriptionPrice: 19.99,
    stats: { posts: 3_100, subscribers: 72_400, likes: 980_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "adult-003",
    username: "maxxmodel",
    displayName: "Maxx Model",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=maxx",
    bannerUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
    bio: "Fitness model and content creator. Exclusive shoots, workout clips, and personal updates.",
    isVerified: true,
    categories: ["Adult", "Fitness"],
    primaryCategory: "Adult",
    subscriptionPrice: 14.99,
    stats: { posts: 1_890, subscribers: 56_100, likes: 745_000 },
    posts: [],
    isFeatured: false,
  },
] as const;
