import type { Creator } from "@/lib/mock-data";

export type CreatorCategory =
  | "All"
  | "Fitness"
  | "Entertainment"
  | "Trading"
  | "Podcasts"
  | "Music"
  | "Art"
  | "Adult";

export const CATEGORIES: readonly CreatorCategory[] = [
  "All",
  "Fitness",
  "Entertainment",
  "Trading",
  "Podcasts",
  "Music",
  "Art",
  "Adult",
] as const;

export interface ExploreCreator extends Creator {
  readonly id: string;
  readonly primaryCategory: CreatorCategory;
  readonly isFeatured: boolean;
}

export const EXPLORE_CREATORS: readonly ExploreCreator[] = [
  // Fitness creators
  {
    id: "fit-001",
    username: "ironmikefitness",
    displayName: "Iron Mike Fitness",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=ironmike",
    bannerUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    bio: "IFBB Pro athlete. Daily workout programs, meal plans, and live coaching sessions. Transform your physique.",
    isVerified: true,
    categories: ["Fitness", "Nutrition"],
    primaryCategory: "Fitness",
    subscriptionPrice: 14.99,
    stats: { posts: 892, subscribers: 24_800, likes: 312_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "fit-002",
    username: "flexqueenrae",
    displayName: "FlexQueen Rae",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=flexqueen",
    bannerUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    bio: "Strength training, powerlifting, and body positivity. Programs for all levels. Glute gains guaranteed.",
    isVerified: true,
    categories: ["Fitness", "Lifestyle"],
    primaryCategory: "Fitness",
    subscriptionPrice: 9.99,
    stats: { posts: 654, subscribers: 18_200, likes: 198_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "fit-003",
    username: "zenflowjake",
    displayName: "ZenFlow Jake",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=zenflow",
    bannerUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    bio: "Yoga, mobility, and mindful movement. Breathwork sessions and flexibility programs for athletes.",
    isVerified: false,
    categories: ["Fitness", "Wellness"],
    primaryCategory: "Fitness",
    subscriptionPrice: 7.99,
    stats: { posts: 423, subscribers: 9_400, likes: 67_000 },
    posts: [],
    isFeatured: false,
  },

  // Entertainment / Adult creators
  {
    id: "ent-001",
    username: "lunavelvet",
    displayName: "Luna Velvet",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=lunavelvet",
    bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    bio: "Exclusive lifestyle content, behind-the-scenes, and personal vlogs. VIP messaging available.",
    isVerified: true,
    categories: ["Entertainment", "Lifestyle"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 19.99,
    stats: { posts: 2_340, subscribers: 67_500, likes: 890_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "ent-002",
    username: "chasewilde",
    displayName: "Chase Wilde",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=chasewilde",
    bannerUrl: "https://images.unsplash.com/photo-1579547945413-497e1b99dac0?w=800&q=80",
    bio: "Comedy skits, roast sessions, and unfiltered takes. The content your timeline is too afraid to post.",
    isVerified: true,
    categories: ["Entertainment", "Comedy"],
    primaryCategory: "Entertainment",
    subscriptionPrice: 12.99,
    stats: { posts: 1_105, subscribers: 31_200, likes: 445_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "adult-001",
    username: "scarlettraven",
    displayName: "Scarlett Raven",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=scarlett",
    bannerUrl: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=800&q=80",
    bio: "Exclusive 18+ content. Custom requests. Daily posts. Free trial for new subscribers.",
    isVerified: true,
    categories: ["Adult", "Lifestyle"],
    primaryCategory: "Adult",
    subscriptionPrice: 24.99,
    stats: { posts: 4_200, subscribers: 89_300, likes: 1_230_000 },
    posts: [],
    isFeatured: true,
  },

  // Trading / Crypto creators
  {
    id: "trade-001",
    username: "cryptosamurai",
    displayName: "CryptoSamurai",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=samurai",
    bannerUrl: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&q=80",
    bio: "On-chain alpha. DeFi strategies, memecoin calls, and portfolio breakdowns. 400%+ ROI in 2025.",
    isVerified: true,
    categories: ["Trading", "Crypto"],
    primaryCategory: "Trading",
    subscriptionPrice: 49.99,
    stats: { posts: 1_870, subscribers: 42_100, likes: 567_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "trade-002",
    username: "wallstwhale",
    displayName: "WallSt Whale",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=whale",
    bannerUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    bio: "Equities, options flow, and macro analysis. Institutional-grade research for retail traders.",
    isVerified: true,
    categories: ["Trading", "Finance"],
    primaryCategory: "Trading",
    subscriptionPrice: 29.99,
    stats: { posts: 780, subscribers: 15_600, likes: 234_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "trade-003",
    username: "nftdegen",
    displayName: "NFT Degen",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=nftdegen",
    bannerUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    bio: "NFT flips, mint alerts, and Web3 alpha. Early access to curated collections and whitelist spots.",
    isVerified: false,
    categories: ["Trading", "NFT"],
    primaryCategory: "Trading",
    subscriptionPrice: 19.99,
    stats: { posts: 520, subscribers: 8_900, likes: 112_000 },
    posts: [],
    isFeatured: false,
  },

  // Podcast / Music creators
  {
    id: "pod-001",
    username: "midnightmikeshow",
    displayName: "Midnight Mike Show",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=midnightmike",
    bannerUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80",
    bio: "Unfiltered late-night podcast. Interviews with founders, athletes, and underground legends. No sponsors.",
    isVerified: true,
    categories: ["Podcasts", "Entertainment"],
    primaryCategory: "Podcasts",
    subscriptionPrice: 9.99,
    stats: { posts: 1_340, subscribers: 53_800, likes: 678_000 },
    posts: [],
    isFeatured: true,
  },
  {
    id: "music-001",
    username: "beatsbynova",
    displayName: "Beats By Nova",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=nova",
    bannerUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    bio: "Producer extraordinaire. Exclusive beats, sample packs, and production tutorials. 10M+ streams.",
    isVerified: true,
    categories: ["Music", "Production"],
    primaryCategory: "Music",
    subscriptionPrice: 14.99,
    stats: { posts: 960, subscribers: 27_400, likes: 345_000 },
    posts: [],
    isFeatured: false,
  },
  {
    id: "music-002",
    username: "acousticember",
    displayName: "Acoustic Ember",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=ember",
    bannerUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    bio: "Singer-songwriter sharing raw acoustic sessions, unreleased tracks, and songwriting breakdowns.",
    isVerified: false,
    categories: ["Music", "Singer-Songwriter"],
    primaryCategory: "Music",
    subscriptionPrice: 6.99,
    stats: { posts: 387, subscribers: 12_100, likes: 89_000 },
    posts: [],
    isFeatured: false,
  },

  // Art creator
  {
    id: "art-001",
    username: "pixelvoid",
    displayName: "PixelVoid",
    avatarUrl: "https://api.dicebear.com/9.x/notionists/svg?seed=pixelvoid",
    bannerUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    bio: "Digital art, AI-generated pieces, and timelapse creation videos. Commissions open for subscribers.",
    isVerified: true,
    categories: ["Art", "Digital Art"],
    primaryCategory: "Art",
    subscriptionPrice: 11.99,
    stats: { posts: 730, subscribers: 19_700, likes: 256_000 },
    posts: [],
    isFeatured: false,
  },
] as const;
